[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
